#!/usr/bin/env python3
"""
Docs Generator Skill - API 문서 자동 생성
"""

import sys
import json
import subprocess
from pathlib import Path


def generate_openapi_docs(project_path: Path):
    """OpenAPI/Swagger 문서 생성"""
    print("📚 API 문서 생성 중...")

    # FastAPI
    main_py = project_path / "main.py"
    if main_py.exists():
        print("   FastAPI 프로젝트 감지")
        print("   OpenAPI 문서: http://localhost:8000/docs")
        print("   ReDoc: http://localhost:8000/redoc")
        return True

    # Express + OpenAPI
    openapi_yaml = project_path / "openapi.yaml"
    if openapi_yaml.exists():
        print("   OpenAPI 스펙 발견: openapi.yaml")
        print("   Swagger UI: npx swagger-ui-watcher openapi.yaml")
        return True

    # Go + Swag
    if (project_path / "docs" / "swagger.yaml").exists():
        print("   Go Swagger 문서 발견")
        return True

    print("⚠️  API 문서 생성 도구를 찾을 수 없습니다.")
    return False


def generate_readme(project_path: Path):
    """README.md 생성/업데이트"""
    readme = project_path / "README.md"

    if readme.exists():
        print("✅ README.md 이미 존재")
        return True

    print("📝 README.md 템플릿 생성 중...")

    project_name = project_path.name

    template = f"""# {project_name}

> Auto-generated by Multi-Agent Coding Team

## 설치

```bash
# TODO: 설치 명령어 추가
```

## 실행

```bash
# TODO: 실행 명령어 추가
```

## API 문서

- Swagger UI: http://localhost:8000/docs (FastAPI)
- ReDoc: http://localhost:8000/redoc

## 테스트

```bash
# TODO: 테스트 명령어 추가
```

## 라이선스

MIT
"""

    with open(readme, 'w', encoding='utf-8') as f:
        f.write(template)

    print(f"✅ README.md 생성 완료: {readme}")
    return True


def main():
    if len(sys.argv) < 2:
        print("Usage: python docs-generator.py <project_path>")
        sys.exit(1)

    project_path = Path(sys.argv[1])

    if not project_path.exists():
        print(f"❌ 프로젝트를 찾을 수 없습니다: {project_path}")
        sys.exit(1)

    print(f"📚 문서 생성기")
    print(f"   프로젝트: {project_path}\n")

    # OpenAPI 문서
    openapi_ok = generate_openapi_docs(project_path)

    # README
    readme_ok = generate_readme(project_path)

    if openapi_ok and readme_ok:
        print("\n✅ 문서 생성 완료!")
        sys.exit(0)
    else:
        print("\n⚠️  일부 문서 생성 실패")
        sys.exit(1)


if __name__ == "__main__":
    main()
